-- =============================================================================
-- Centurai Print OS - Staging Database Setup Script
-- Run this complete script in your new Supabase project's SQL Editor.
-- =============================================================================

-- 1. Create orders table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone TEXT,
  email TEXT,
  ordername TEXT,
  material TEXT,
  color TEXT,
  notes TEXT,
  fileurl TEXT,
  filesize BIGINT,
  status TEXT DEFAULT 'queued',
  priority INTEGER DEFAULT 0,
  weightgrams NUMERIC DEFAULT 0,
  pricepergram NUMERIC DEFAULT 3,
  totalprice NUMERIC DEFAULT 0,
  tracking_code TEXT UNIQUE,
  assigned_printer TEXT,
  createdat TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create site_config table
CREATE TABLE IF NOT EXISTS site_config (
  id INTEGER PRIMARY KEY DEFAULT 1,
  brand_name TEXT DEFAULT 'JUST print',
  hero_title TEXT DEFAULT 'Your Idea.
Made Real.',
  hero_subtitle TEXT DEFAULT 'Upload your 3D design, pick your material, and we''ll print it for you -- fast, affordable, and right here on campus.',
  why_title TEXT DEFAULT 'Why Print With Us?',
  why_text TEXT DEFAULT 'We''re students who love making things. Our setup is tuned for speed and precision, so you get your parts fast without breaking the bank. PLA, PETG, ABS, Carbon Fiber, TPU -- we''ve got what you need.',
  price_per_gram NUMERIC DEFAULT 3,
  materials TEXT DEFAULT 'PLA, PETG, ABS, Carbon Fiber, TPU',
  colors TEXT DEFAULT 'McLaren Orange, Carbon Black, White, Silver, Red',
  whatsapp_number TEXT DEFAULT '',
  instagram_link TEXT DEFAULT '',
  email_address TEXT DEFAULT '',
  show_socials BOOLEAN DEFAULT TRUE,
  privacy_policy TEXT DEFAULT '',
  announcement_text TEXT DEFAULT '',
  announcement_active BOOLEAN DEFAULT FALSE
);

-- Seed default site configuration
INSERT INTO site_config (id, brand_name, hero_title, hero_subtitle, why_title, why_text, price_per_gram, materials, colors)
VALUES (
  1,
  'JUST print',
  'Your Idea.
Made Real.',
  'Upload your 3D design, pick your material, and we''ll print it for you -- fast, affordable, and right here on campus.',
  'Why Print With Us?',
  'We''re students who love making things. Our setup is tuned for speed and precision, so you get your parts fast without breaking the bank. PLA, PETG, ABS, Carbon Fiber, TPU -- we''ve got what you need.',
  3,
  'PLA, PETG, ABS, Carbon Fiber, TPU',
  'McLaren Orange, Carbon Black, White, Silver, Red'
)
ON CONFLICT (id) DO NOTHING;

-- 3. Create gallery_items table
CREATE TABLE IF NOT EXISTS gallery_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  description TEXT DEFAULT '',
  media_urls TEXT DEFAULT '',
  cover_url TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery_items ENABLE ROW LEVEL SECURITY;

-- 5. Policies for site_config
DROP POLICY IF EXISTS "Public can read site config" ON site_config;
DROP POLICY IF EXISTS "Admin can manage site config" ON site_config;

CREATE POLICY "Public can read site config"
  ON site_config FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Admin can manage site config"
  ON site_config FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 6. Policies for orders
DROP POLICY IF EXISTS "Public can insert orders" ON orders;
DROP POLICY IF EXISTS "Admin can manage orders" ON orders;

CREATE POLICY "Public can insert orders"
  ON orders FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Admin can manage orders"
  ON orders FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 7. Policies for gallery_items
DROP POLICY IF EXISTS "Gallery items are viewable by everyone" ON gallery_items;
DROP POLICY IF EXISTS "Authenticated users can insert gallery items" ON gallery_items;
DROP POLICY IF EXISTS "Authenticated users can update gallery items" ON gallery_items;
DROP POLICY IF EXISTS "Authenticated users can delete gallery items" ON gallery_items;

CREATE POLICY "Gallery items are viewable by everyone"
  ON gallery_items FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert gallery items"
  ON gallery_items FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can update gallery items"
  ON gallery_items FOR UPDATE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can delete gallery items"
  ON gallery_items FOR DELETE
  TO authenticated
  USING (true);

-- 8. Storage Buckets (stl-files and gallery-media)
INSERT INTO storage.buckets (id, name, public)
VALUES ('stl-files', 'stl-files', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('gallery-media', 'gallery-media', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for stl-files
DROP POLICY IF EXISTS "Public can upload stl-files" ON storage.objects;
DROP POLICY IF EXISTS "Public can read stl-files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete stl-files" ON storage.objects;

CREATE POLICY "Public can upload stl-files"
  ON storage.objects FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'stl-files');

CREATE POLICY "Public can read stl-files"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'stl-files');

CREATE POLICY "Authenticated users can delete stl-files"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'stl-files');

-- Storage policies for gallery-media
DROP POLICY IF EXISTS "Gallery media is publicly accessible" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload gallery media" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete gallery media" ON storage.objects;

CREATE POLICY "Gallery media is publicly accessible"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'gallery-media');

CREATE POLICY "Authenticated users can upload gallery media"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'gallery-media');

CREATE POLICY "Authenticated users can delete gallery media"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'gallery-media');

-- 9. RPC Functions
CREATE OR REPLACE FUNCTION get_queued_count()
RETURNS integer
SECURITY DEFINER
AS $$
DECLARE
  cnt integer;
BEGIN
  SELECT count(*) INTO cnt FROM orders WHERE status = 'queued';
  RETURN cnt;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION search_orders(q text)
RETURNS SETOF orders
SECURITY DEFINER
AS $$
BEGIN
  IF length(trim(q)) < 3 THEN
    RETURN;
  END IF;
  RETURN QUERY SELECT * FROM orders 
  WHERE tracking_code ILIKE q 
     OR phone ILIKE '%' || q || '%';
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_saved_orders(codes text[])
RETURNS SETOF orders
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY SELECT * FROM orders 
  WHERE tracking_code = ANY(codes);
END;
$$ LANGUAGE plpgsql;

-- 10. Enable Realtime updates on tables
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE orders;
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'site_config'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE site_config;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'gallery_items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE gallery_items;
  END IF;
END $$;
